config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/frees_controller.rb
class FreesController < ApplicationController
  before_action :set_free, only: [:show, :edit, :update, :destroy]

  # GET /frees
  # GET /frees.json
  def index
    @frees = Free.all
  end

  # GET /frees/1
  # GET /frees/1.json
  def show
  end

  # GET /frees/new
  def new
    @free = Free.new
  end

  # GET /frees/1/edit
  def edit
  end

  # POST /frees
  # POST /frees.json
  def create
    @free = Free.new(free_params)

    respond_to do |format|
      if @free.save
        format.html { redirect_to @free, notice: 'Free was successfully created.' }
        format.json { render :show, status: :created, location: @free }
      else
        format.html { render :new }
        format.json { render json: @free.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frees/1
  # PATCH/PUT /frees/1.json
  def update
    respond_to do |format|
      if @free.update(free_params)
        format.html { redirect_to @free, notice: 'Free was successfully updated.' }
        format.json { render :show, status: :ok, location: @free }
      else
        format.html { render :edit }
        format.json { render json: @free.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frees/1
  # DELETE /frees/1.json
  def destroy
    @free.destroy
    respond_to do |format|
      format.html { redirect_to frees_url, notice: 'Free was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_free
      @free = Free.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def free_params
      params.require(:free).permit(:speaking, :lesson, :description, :image_url, :string)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

def index
end

def show
end

def new
end 

def create
end

def destroy
end 

end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.limit(3)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end

  def landing_page
    @featured_product = Product.limit(3)
    @products = Product.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frees_helper.rb
module FreesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ielts</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js">
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Online IELTS</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/products">Books</a></li>
        <li><a href="/static_pages/about">About</a></li>
        <li><a href="/static_pages/contact">Contact</a></li> 
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="#">100% Online IELTS Prep</a></li>
        <li><a href="#">Student Success Stories</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

  
 <%= yield %>   

  </body>

<footer>

  &copy; 2016 Online IELTS
</footer>


</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="container">
    <div class="row">
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div><!--END error_explanation -->
      <% end %>

      <div class="col-md-4 col-md-offset-4">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Name' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, rows: '5', class: 'form-control', placeholder: 'Description' %>
        </div>

        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, class: 'form-control', placeholder: 'Price' %>
        </div>

        <div class="form-group">
          <%= f.label :image_url %>
          <%= f.text_field :image_url, class: 'form-control', placeholder: 'Image URL' %>
        </div>
        <br><br>
        <div class="actions">
          <%= f.submit class: 'btn btn-default' %>
        </div>
      </div><!--END col-md-4 col-md-offset-4-->
    </div><!--END row-->
  </div><!--END container-->
<% end %>

app/views/products/_product.html.erb
<% @products.each do |product| %>
      <div class="booyah-box-show col-xs-10 col-xs-offset-1">
         <%= image_tag(product.image_url, class: "img-responsive")  %>
         <%= product.name %>
         <%= product.price %>
         <%= product.description %>
         <%= link_to product.name, product_path(product), :class => "btn-default" %>
         <%= link_to 'Show', product, :class => "btn btn-default"%>
         <%= link_to 'Edit', edit_product_path(product),:class => "btn btn-default" %>
         <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>
          <br />
          <br />
          <br />
      </div>

    <% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Our Exclusive Guide to IELTS Success</h2>
      
    </div><!--end header div-->
  </div>


  

<%= link_to 'New Product', new_product_path %>
<div class="container-fluid">
  <div class="row">
    <%= render @products %>
    
 


      
  

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<h2>The Complete Guide to IELTS Success</h2>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<h3>Everything You Need to Know About IELTS</h3>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<div class="booyah-box-show col-xs-10 col-xs-offset-1">
<p>
  <strong>Image url:</strong>
  <%= image_tag(@product.image_url, class: "img-responsive")%>
</p>
</div>


<p>
  <strong>Price:</strong>
  <%= @product.price %>
  
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-xs-4 col-xs-offset-1">
      <h2>Who We Are</h2>
      <p><p>It's not surprising that you've never heard of us, we've been working!</p>
      <p>But after years and years of seeing students struggle to master the IELTS exam, we've decided to matters into our own hands. This course is handcrafted to provide the most comprehensive IELTS training, specifically targeted at highly motivated learners who are looking to iron out nagging English mistakes.Here's what you'll learn.</p>
    </div><!-- /col -->

    <div class="col-xs-4 col-xs-offset-1">
      <h2>What We Teach</h2>
      <div class="skills-column">
        <ul id= "skills-list">
          <li>Reading</li>
          <li>Writing</li>
          <li>Listening</li>
          <li>Speaking</li>
        </ul>
      </div> <!--end skills column -->
    </div><!-- /col -->

    <div class="col-xs-4 col-xs-offset-1">
      <h2>Our Story</h2>
      <p>Underpaid and overeducated is a common theme for my generation. Countless number of people just like myself are sitting around wondering what to do with themselves after they've given their last dollar to the almight gods of higher education and are now simply left holding a bill. </p>

      <p>No job. No girlfriend. No progress. No leads. Not even a clear skill set. A 
          lot of people know about stuff, few know how to do stuff. </p>

      <p>I wanted to be different. </p>

      <p>So I set off to Vietnam, not knowing what it would give to me and I put my head down and worked. And worked. And worked some more. Along the way, however, I realized that no one should ever have to feel that way--desperate and without a plan, feeling constant overwhelmed. </p>

      <p>So I decided that I'd help people not have to.</p>.

      <p>With little money of our own and not a whole hell of a lot of business experience to start, we decided that we'd empower people with what we know: English and IELTS training. But not like other schools. The core of our business model starts with understanding that no one should have to suffer as we did. No one should have to "figure things out." Other schools may have more advanced equipment or more modern facilities, but you won't find a place that puts the concerns of their students abover everything else like we do. This is the heart of our business. </p>

    </div><!-- /col -->
  </div><!-- /row -->
</div> <!-- /container -->
    

app/views/static_pages/contact.html.erb
<div id="container">
  <h1>Dan Carey and Calum Nicolson</h1>
  <!-- Contact -->
  <div data-stellar-background-ratio=".5"></div>

  <div class="container anchor" id="info">
    <div class="header-contact">
      <h3>Start Your Journey</h3>
    </div><!--end header div-->

     <div class="col-md-4">
         <%= image_tag("The_Complete_Guide_to_IELTS_Success.jpg", class: "img-responsive") %>" 
          <p><br><a class="btn btn-default" href="products/8" role="button">Sign Up Now and Get 75% Off &raquo;</a></p>
      </div>

    

        <div class="col-md-6 col-sm-6 col-xs-12">
          <form>
            <div class="form-group">
              <label for="name">*Your Name</label>
              <input type="text" class="form-control" id="name" required="required" title="(*)Name"placeholder="Enter Name">
            </div>

            <div class="form-group">
              <label for="email">*Your Email</label>
              <input type="email" class="form-control" id="email" required="required" title="(*)Email" placeholder="Enter Email">
              <label for="paragraph">Your Message</label>
              <textarea placeholder="Enter Message" style="resize:none" required='required' class="form-control" class="message-box" id="paragraph" cols="40" rows="5"></textarea>
              <br>
              <button type="submit" class="btn btn-success contact-submit" id="button">Submit</button>
            </div>
          </form>
        </div><!--end grid div-->
      </div><!--end row div-->
    </div><!--end contactinfo div-->
  </div><!--end contact form div-->   
</div><!--end container div--> 

app/views/static_pages/index.html.erb
<%= image_tag("vietnam.jpg", class: "img-responsive") %>

app/views/static_pages/landing_page.html.erb
<h2>Featured Product:</h2>
<%= @featured_product.name %>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
    <br />
    <div class="item<%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url) %>
      <br />
      <div class="carousel-caption">
        <%= product.name %>
        <br />
      </div>
        </div>
        <% end %>
  </div>
</div>


   

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>